name: Update Commit Activity Badges

on:
  push:
    branches:
      - main
  schedule:
    - cron: '59 23 * * *'
  workflow_dispatch:

jobs:
  update-commit-badges:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: main
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Git Config
        run: |
          git config --global user.email "github-actions[bot]@github.com"
          git config --global user.name "github-actions[bot]"

      - name: Count Total Commit Days
        id: total_commit_days
        run: |
          git log --format='%cd' --date=format:'%Y-%m-%d' | sort -u
          total_days=$(git log --format='%cd' --date=format:'%Y-%m-%d' | sort -u | wc -l)
          echo "total_commit_days=$total_days" >> $GITHUB_ENV

      - name: Count Weekly Commit Days
        id: weekly_commit_days
        run: |
          git log --since='7 days ago' --format='%cd' --date=format:'%Y-%m-%d' | sort -u
          weekly_days=$(git log --since='7 days ago' --format='%cd' --date=format:'%Y-%m-%d' | sort -u | wc -l)
          echo "weekly_commit_days=$weekly_days" >> $GITHUB_ENV

      - name: Create Badges
        run: |
          total_badge_url="https://img.shields.io/badge/total_commit_days-${{ env.total_commit_days }}-blue?cache=$(date +%s)"
          weekly_badge_url="https://img.shields.io/badge/weekly_commit_days-${{ env.weekly_commit_days }}-green?cache=$(date +%s)"
          echo "![Total Commit Days]($total_badge_url)" > total_commit_badge.md
          echo "![Weekly Commit Days]($weekly_badge_url)" > weekly_commit_badge.md

      - name: Update README with Badges at Top
        run: |
          sed -i '/Total Commit Days/d' README.md
          sed -i '/Weekly Commit Days/d' README.md
          cat total_commit_badge.md weekly_commit_badge.md README.md > temp_readme.md
          mv temp_readme.md README.md

      - name: Stash Changes (if any) before Pull
        run: |
          git add .
          git stash save "temp-stash-for-pull" || echo "Nothing to stash"

      - name: Pull Latest Changes
        run: |
          git pull origin main --rebase

      - name: Apply Stash (if any)
        run: |
          git stash pop || echo "No stash to apply"

      - name: Commit Changes
        run: |
          git add README.md
          git commit -m "Update commit days badges" || echo "No changes to commit"

      - name: Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git push https://x-access-token:${GH_PAT}@github.com/TIL-challenge/becooq81.git
