name: Update Commit Activity Badge

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly on Sunday
  workflow_dispatch:  # Allows manual run

jobs:
  update-commit-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: main  # Change this if using a different branch
          persist-credentials: true  # Ensure GitHub token is used

      - name: Setup Git Config
        run: |
          git config --global user.email "github-actions[bot]@github.com"
          git config --global user.name "github-actions[bot]"

      - name: Count Commit Days
        id: count_days
        run: |
          # Count unique commit days
          days=$(git log --since='7 days ago' --format='%cd' --date=format:'%A' | sort -u | wc -l)
          echo "Commit days found: $days"
          echo "commit_days=$days" >> $GITHUB_ENV
          echo "::set-output name=commit_days::$days"

      - name: Create Badge
        run: |
          # Create badge URL with cache-busting parameter to force refresh
          badge_url="https://img.shields.io/badge/commit_days-${{ env.commit_days }}-green?cache=$(date +%s)"
          echo "Badge URL: $badge_url"
          echo "url=$badge_url" >> $GITHUB_ENV
          echo "![Commit Days](${badge_url})" > commit_badge.md

      - name: Update README with Badge
        run: |
          # Remove old badge line if exists and append new badge
          sed -i '/Commit Days/d' README.md
          cat commit_badge.md >> README.md

      - name: Commit Changes
        run: |
          git add README.md
          git status  # Check if changes are staged correctly
          git commit -m "Update commit days badge"

      - name: Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # Ensure this token has push permissions
        run: |
          # Push changes back to GitHub using the PAT
          git push https://x-access-token:${GH_PAT}@github.com/TIL-challenge/becooq81.git
